### ISSUE TITLE
Does the website ever get updated

### ISSUE THREAD

**Issue by JugglerX** [drjekyllthemes/themes#133]
I submitted a theme (Serif) and the PR was accepted months ago. But the theme still does not appear on the website? Does the website get updated any more?

**Comment by geraldb** [comment]
I'm not a machine. Thank you.  There's nobody here just a random guy.

**Comment by JugglerX** [comment]
Well I wasn't really meaning to be offensive, I understand this is a free project. I think it's a fair question. I just want to know whats going on and if maybe I'm not seeing the theme for some reason. Otherwise if you are busy and no longer updating the website I will not do further submissions.
