### ISSUE TITLE
Questions about this project

### ISSUE THREAD

**Issue by jacobtomlinson** [drjekyllthemes/themes#2]
Thanks for your effort on this project! This is something @ariestiyansyah and I tried to do when we saw that the original Jekyll themes wasn't being maintained, however that died when the original maintainer came back and said he was going to look after it (which hasn't happened yet). 

I have a few questions about your project though.

* Why have you moved away from the standard Jekyll structure (`_posts`, etc)?
* What was your reasoning behind putting all themes in one monolithic file?
* What are your motives behind running the project? I see you've put an announcement (advert) on it
* Are you interested in having other maintainers on the project?

**Comment by geraldb** [comment]
Great questions. Please post your questions to the Jekyll talk forum. Cheers.
