### ISSUE TITLE
Theme thumbnail is not updated in live website?

### ISSUE THREAD

**Issue by PanosSakkos** [drjekyllthemes/themes#22]
Hi!

I'm maintaining the { Personal } repository and I had a look at http://drjekyllthemes.github.io/ and noticed that the updated thumbnail is not rendered.

The updated thumbnail is [here] (https://github.com/drjekyllthemes/themes/blob/master/thumbnails/personal.jpg).

Thanks!
:panos

**Comment by geraldb** [comment]
Thanks for the reminder. FYI: The themes get linked in via git submodules (and the submodule needs to get updated/synced). Cheers..

**Comment by PanosSakkos** [comment]
Cool! Thanks!

**Comment by geraldb** [comment]
FYI: Thanks for your patience. Updated git submodule (and site).

**Comment by sharadcodes** [comment]
When will the site be updated again ?

**Comment by geraldb** [comment]
FYI: I'm not a robot. There's nobody here. It's just my humble self.
