### ISSUE TITLE
Materialized Theme is not displaying

### ISSUE THREAD

**Issue by lpsandaruwan** [drjekyllthemes/themes#81]
Hi,

Seems like the theme I added is not displaying on the website. Can you please take a look?

```
- title:        Materialized
  home_url:     https://github.com/lpsandaruwan/materialized
  download_url: https://github.com/lpsandaruwan/materialized/archive/master.zip
  demo_url:     http://lahiru.site/materialized
  author:       Lahiru Pathirage
  thumbnail:    materialized.png
  license:      GPLv3
  tags:        [angular, material, responsive]
```

Thanks. :-)

**Comment by geraldb** [comment]
@lpsandaruwan  Sorry all new themes get published on the site with the next update (that is, get included via a git module). Thanks for the patience. Only the drjekyll package manager uses direct acces. Cheers.
